# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/aidan/Documents/school/ee454/ee454edgeDetector/pong/pong.cache/wt [current_project]
set_property parent.project_path C:/Users/aidan/Documents/school/ee454/ee454edgeDetector/pong/pong.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/aidan/Documents/school/ee454/ee454edgeDetector/pong/hvsync_generator.v
  C:/Users/aidan/Documents/school/ee454/ee454edgeDetector/pong/pong.v
}
read_xdc C:/Users/aidan/Documents/school/ee454/ee454edgeDetector/pong/Lab2.xdc
set_property used_in_implementation false [get_files C:/Users/aidan/Documents/school/ee454/ee454edgeDetector/pong/Lab2.xdc]

synth_design -top pong -part xc7a100tcsg324-1
write_checkpoint -noxdef pong.dcp
catch { report_utilization -file pong_utilization_synth.rpt -pb pong_utilization_synth.pb }
